spring:
  application:
    name: onboarding-and-identity-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://${DB_HOST:10.212.10.135}:${DB_PORT:5432}/${DB_NAME:identity}}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 5000
      validation-timeout: 3000
      initialization-fail-timeout: 0
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail.smtp.auth: ${MAIL_SMTP_AUTH:false}
      mail.smtp.starttls.enable: ${MAIL_SMTP_STARTTLS:false}

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info

services:
  authentication:
    url: http://localhost:8082

keycloak:
  admin:
    base-url: ${KEYCLOAK_URL:http://localhost:8085}
    target-realm: ${KEYCLOAK_TARGET_REALM:identity-os}
    admin-realm: ${KEYCLOAK_ADMIN_REALM:master}
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
    user-client-id: ${KEYCLOAK_USER_CLIENT_ID:identity-os-app-users}
    username: ${KEYCLOAK_ADMIN_USERNAME:admin}
    password: ${KEYCLOAK_ADMIN_PASSWORD:admin}

organization-registration:
  mail:
    from: ${ORG_REGISTRATION_MAIL_FROM:no-reply@identity-os.local}
