package com.identityos.onboarding_and_identity_service.dto;

public record OrganizationProfileResponse(
        String organizationId,
        String organizationName,
        String organizationType,
        String countryCode,
        String officialEmail,
        String officialPhone,
        String registrationNumber,
        String registrationAuthority,
        String verificationIdType,
        String verificationId,
        String verificationIdVerifyStatus,
        String websiteUrl,
        String logoUrl,
        String status,
        String approvalStatus,
        String representativeFirstName,
        String representativeLastName,
        String representativeDesignation,
        String representativeEmail,
        String representativeMobileNumber,
        String representativeEmployeeId,
        String addressType,
        String addressLine1,
        String addressLine2,
        String city,
        String district,
        String state,
        String postalCode,
        String addressCountryCode,
        String addressProofRef
) {
    public OrganizationProfileResponse(
            String organizationId,
            String organizationName,
            String organizationType,
            String countryCode,
            String officialEmail,
            String officialPhone,
            String registrationNumber,
            String registrationAuthority,
            String verificationIdType,
            String verificationId,
            String verificationIdVerifyStatus,
            String websiteUrl,
            String logoUrl,
            String status,
            String approvalStatus) {
        this(
                organizationId,
                organizationName,
                organizationType,
                countryCode,
                officialEmail,
                officialPhone,
                registrationNumber,
                registrationAuthority,
                verificationIdType,
                verificationId,
                verificationIdVerifyStatus,
                websiteUrl,
                logoUrl,
                status,
                approvalStatus,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null);
    }
}
